/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class blogs {
	constructor() {
		this.id = undefined
		this.image = undefined
		this.largeImage = undefined
		this.author = undefined
		this.date = undefined
		this.view = undefined
		this.title = undefined
		this.slug_title = undefined
		this.excerpt = undefined
		this.body = undefined
	}

	setId(id) {
		this.id = id
	}

	getId() {
		return this.id
	}

	setImage(image) {
		this.image = image
	}

	getImage() {
		return this.image
	}

	setLargeImage(largeImage) {
		this.largeImage = largeImage
	}

	getLargeImage() {
		return this.largeImage
	}

	setAuthor(author) {
		this.author = author
	}

	getAuthor() {
		return this.author
	}

	setDate(date) {
		this.date = date
	}

	getDate() {
		return this.date
	}

	setView(view) {
		this.view = view
	}

	getView() {
		return this.view
	}

	setTitle(title) {
		this.title = title
	}

	getTitle() {
		return this.title
	}

	setSlug_title(slug_title) {
		this.slug_title = slug_title
	}

	getSlug_title() {
		return this.slug_title
	}

	setExcerpt(excerpt) {
		this.excerpt = excerpt
	}

	getExcerpt() {
		return this.excerpt
	}

	setBody(body) {
		this.body = body
	}

	getBody() {
		return this.body
	}
}

blogs.className = 'blogs'

export { blogs }
