/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class events {
  constructor() {
    this.id = undefined;
    this.name = "";
    this.description = "";
    this.date = undefined;
    this.local_name = undefined;
    this.local_address = undefined;
    this.slug_name = undefined;
    this.speakers = undefined;
    this.moderator = undefined;
    this.organizer = undefined;
    this.imgs = undefined;
    this.state = undefined;
  }

  setId(id) {
    this.id = id;
  }

  getId() {
    return this.id;
  }

  setName(name) {
    this.name = name;
  }

  getName() {
    return this.name;
  }

  setDescription(description) {
    this.description = description;
  }

  getDescription() {
    return this.description;
  }

  setDate(date) {
    this.date = date;
  }

  getDate() {
    return this.date;
  }

  setLocal_name(local_name) {
    this.local_name = local_name;
  }

  getLocal_name() {
    return this.local_name;
  }

  setLocal_address(local_address) {
    this.local_address = local_address;
  }

  getLocal_address() {
    return this.local_address;
  }

  setSlug_name(slug_name) {
    this.slug_name = slug_name;
  }

  getSlug_name() {
    return this.slug_name;
  }

  setSpeakers(speakers) {
    this.speakers = speakers;
  }

  getSpeakers() {
    return this.speakers;
  }

  setModerator(moderator) {
    this.moderator = moderator;
  }

  getModerator() {
    return this.moderator;
  }

  setOrganizer(organizer) {
    this.organizer = organizer;
  }

  getOrganizer() {
    return this.organizer;
  }

  setImgs(imgs) {
    this.imgs = imgs;
  }

  getImgs() {
    return this.imgs;
  }

  setState(state) {
    this.state = state;
  }

  getState() {
    return this.state;
  }
}

events.className = "events";

export { events };
