/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class events {
  constructor() {
    this.id = undefined
    this.slug_name = undefined
    this.state = undefined
    this.locName = undefined
    this.locAddress = undefined
    this.name = undefined
    this.date = undefined
    this.description = undefined
  }

  setId(id) {
    this.id = id
  }

  getId() {
    return this.id
  }

  setSlug_name(slug_name) {
    this.slug_name = slug_name
  }

  getSlug_name() {
    return this.slug_name
  }

  setState(state) {
    this.state = state
  }

  getState() {
    return this.state
  }

  setLocName(locName) {
    this.locName = locName
  }

  getLocName() {
    return this.locName
  }

  setLocAddress(locAddress) {
    this.locAddress = locAddress
  }

  getLocAddress() {
    return this.locAddress
  }

  setName(name) {
    this.name = name
  }

  getName() {
    return this.name
  }

  setDate(date) {
    this.date = date
  }

  getDate() {
    return this.date
  }

  setDescription(description) {
    this.description = description
  }

  getDescription() {
    return this.description
  }
}

events.className = 'events'

export { events }
