/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class medium {
  constructor() {
    this.id = undefined;
    this.api = undefined;
  }

  setId(id) {
    this.id = id;
  }

  getId() {
    return this.id;
  }

  setApi(api) {
    this.api = api;
  }

  getApi() {
    return this.api;
  }
}

medium.className = "medium";

export { medium };
