/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class navbarName {
    constructor() {
        this.schoolName = undefined;
    }

    setSchoolName(schoolName) {
        this.schoolName = schoolName;
    }

    getSchoolName() {
        return this.schoolName;
    }
}

navbarName.className = 'navbarName';

export {navbarName}