/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class teams {
  constructor() {
    this.id = undefined;
    this.name = "";
    this.img = undefined;
    this.age = 0;
    this.position = "";
    this.department = "";
    this.class_year = "";
    this.linkedin = undefined;
    this.github = undefined;
    this.mail = undefined;
    this.twitter = undefined;
  }

  setId(id) {
    this.id = id;
  }

  getId() {
    return this.id;
  }

  setName(name) {
    this.name = name;
  }

  getName() {
    return this.name;
  }

  setImg(img) {
    this.img = img;
  }

  getImg() {
    return this.img;
  }

  setAge(age) {
    this.age = age;
  }

  getAge() {
    return this.age;
  }

  setPosition(position) {
    this.position = position;
  }

  getPosition() {
    return this.position;
  }

  setDepartment(department) {
    this.department = department;
  }

  getDepartment() {
    return this.department;
  }

  setClass_year(class_year) {
    this.class_year = class_year;
  }

  getClass_year() {
    return this.class_year;
  }

  setLinkedin(linkedin) {
    this.linkedin = linkedin;
  }

  getLinkedin() {
    return this.linkedin;
  }

  setGithub(github) {
    this.github = github;
  }

  getGithub() {
    return this.github;
  }

  setMail(mail) {
    this.mail = mail;
  }

  getMail() {
    return this.mail;
  }

  setTwitter(twitter) {
    this.twitter = twitter;
  }

  getTwitter() {
    return this.twitter;
  }
}

teams.className = "teams";

export { teams };
