/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class teams {
  constructor() {
    this.id = undefined
    this.img = undefined
    this.name = undefined
    this.designation = undefined
    this.twitter = undefined
    this.linkedin = undefined
    this.github = undefined
  }

  setId(id) {
    this.id = id
  }

  getId() {
    return this.id
  }

  setImg(img) {
    this.img = img
  }

  getImg() {
    return this.img
  }

  setName(name) {
    this.name = name
  }

  getName() {
    return this.name
  }

  setDesignation(designation) {
    this.designation = designation
  }

  getDesignation() {
    return this.designation
  }

  setTwitter(twitter) {
    this.twitter = twitter
  }

  getTwitter() {
    return this.twitter
  }

  setLinkedin(linkedin) {
    this.linkedin = linkedin
  }

  getLinkedin() {
    return this.linkedin
  }

  setGithub(github) {
    this.github = github
  }

  getGithub() {
    return this.github
  }
}

teams.className = 'teams'

export { teams }
