/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class teams {
    constructor() {
        this.id = undefined;
        this.name = undefined;
        this.slug_name = undefined;
        this.designation = undefined;
        this.image = undefined;
        this.twitter = undefined;
        this.linkedin = undefined;
        this.github = undefined;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setName(name) {
        this.name = name;
    }

    getName() {
        return this.name;
    }

    setSlug_name(slug_name) {
        this.slug_name = slug_name;
    }

    getSlug_name() {
        return this.slug_name;
    }

    setDesignation(designation) {
        this.designation = designation;
    }

    getDesignation() {
        return this.designation;
    }

    setImage(image) {
        this.image = image;
    }

    getImage() {
        return this.image;
    }

    setTwitter(twitter) {
        this.twitter = twitter;
    }

    getTwitter() {
        return this.twitter;
    }

    setLinkedin(linkedin) {
        this.linkedin = linkedin;
    }

    getLinkedin() {
        return this.linkedin;
    }

    setGithub(github) {
        this.github = github;
    }

    getGithub() {
        return this.github;
    }
}

teams.className = 'teams';

export { teams };